services:
  ml_service:
    build: ml_service/
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db

  mqtt_service:
    build: mqtt_service/
    restart: always
    depends_on:
      - db
      - mosquitto

  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: readings
    volumes:
      - my_db:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    command: php -S 0.0.0.0:8080 -t /var/www/html # This command is only needed when the host doesn't support IPv6
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  mosquitto:
    build: mosquitto_broker/
    restart: always
    ports:
      - 1883:1883
volumes:
  my_db:
