name: My Python test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  do_stuff_yeah:
    runs_on: ubuntu-latest
    steps:
    - name: Checking stuff out to remote machine where code will run
      uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Pytest
      run: |
        pytest
